version: 2
jobs:
  build:
    working_directory: ~/todo-list-ng
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: todo-list-ng-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: todo-list-ng-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  
  deploy:
    working_directory: ~/todo-list-ng
    steps:
      - checkout
      - run: npm run deploy --base-href=/todo-list-ng/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
